CREATE DATABASE IF NOT EXISTS ${database-name};

USE ${database-name};

CREATE TABLE IF NOT EXISTS users(
    username VARCHAR(255) PRIMARY KEY,
    password_h VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS games(
    game_id INT PRIMARY KEY,
    white_username VARCHAR(255),
    black_username VARCHAR(255),
    game_name VARCHAR(255) NOT NULL,
    game_data VARCHAR(10000) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    FOREIGN KEY (white_username) REFERENCES users(username),
    FOREIGN KEY (black_username) REFERENCES users(username)
);

CREATE TABLE IF NOT EXISTS authentication(
    username VARCHAR(255) PRIMARY KEY,
    auth_token VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
    FOREIGN KEY (username) REFERENCES users(username)
);